import turtle

#square
qazi_turtle = turtle.Turtle()
qazi_turtle.speed(30)


def square():
    
    qazi_turtle.forward(100)
    qazi_turtle.right(90)
    qazi_turtle.forward(100)
    qazi_turtle.right(90)
    qazi_turtle.forward(100)
    qazi_turtle.right(90)
    qazi_turtle.forward(100)
#square()
#qazi_turtle.forward(300)
#square()

#elephent_weight=3000
#ant_weight=.01
#if elephent_weight < ant_weight:

    
    #square()
#else:
        #qazi_turtle.forward(100)
#qazi="sad"
#while qazi=="happy":
    #qazi_turtle.forward(10)

for count in range(12):
    square()
        

 
    
